---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: katib-postgres
  namespace: kubeflow
  labels:
    katib.kubeflow.org/component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      katib.kubeflow.org/component: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        katib.kubeflow.org/component: postgres
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: katib-postgres
          image: postgres:14.3-alpine
          envFrom:
          - secretRef:
              name: katib-postgres-secrets
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          # readinessProbe:
          #   exec:
          #     command:
          #       - "/bin/bash"
          #       - "-c"
          #       - "mysql -D ${MYSQL_DATABASE} -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1'"
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   failureThreshold: 10
          # livenessProbe:
          #   exec:
          #     command:
          #       - "/bin/bash"
          #       - "-c"
          #       - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   failureThreshold: 10
          # startupProbe:
          #   exec:
          #     command:
          #       - "/bin/bash"
          #       - "-c"
          #       - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          #   periodSeconds: 15
          #   failureThreshold: 60
      #     volumeMounts:
      #       - name: katib-mysql
      #         mountPath: /var/lib/mysql
      # volumes:
      #   - name: katib-mysql
      #     persistentVolumeClaim:
      #       claimName: katib-mysql
