---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: katib-db-manager
  namespace: kubeflow
  labels:
    katib.kubeflow.org/component: db-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      katib.kubeflow.org/component: db-manager
  template:
    metadata:
      labels:
        katib.kubeflow.org/component: db-manager
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: katib-db-manager
          image: cr.makina.rocks/library/katib-db-manager:test
          env:
            - name: DB_NAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "katib"
          command:
            - "./katib-db-manager"
          ports:
            - name: api
              containerPort: 6789
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:6789"]
            initialDelaySeconds: 10
            periodSeconds: 60
            failureThreshold: 5
